// Daily "mark ended" runner. Flips `status` from `live` to `ended` on rows
// that are entirely in the past — never deletes, per DATA.md's "past one-offs
// are retained, not deleted." Opens/updates a review PR; never writes to main
// directly (same shape as scripts/scrape.mjs).
//
//   node scripts/mark-ended.mjs            # apply changes + write mark-ended-report.md
//   node scripts/mark-ended.mjs --dry-run  # report only, write nothing
//
// Two independent checks, both driven by DATA.md:
//  - oneoffs.csv: a `live` row whose last day (`end_date` || `date`) is before
//    today is entirely in the past → `status=ended`. This is exactly the
//    condition validate-data.mjs's CI gate fails a PR on ("mark it
//    status=ended"), so this job keeps the fleet from ever tripping it.
//  - series.csv: a `live` row with a `valid_to` before today has finished its
//    run → `status=ended` ("End a series" in DATA.md).
//
// Surgical text write: replace only the changed lines, as text, never
// re-serialize the whole file — see scrape.mjs's file header for why.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import Papa from 'papaparse';
import { validateData } from './validate-data.mjs';

const DATA_DIR = path.join(process.cwd(), 'data');
const ONEOFFS_PATH = path.join(DATA_DIR, 'oneoffs.csv');
const SERIES_PATH = path.join(DATA_DIR, 'series.csv');
const REPORT_PATH = path.join(process.cwd(), 'mark-ended-report.md');
const DRY_RUN = process.argv.includes('--dry-run');

const ONEOFF_FIELDS = [
  'id', 'name', 'style', 'venue_id', 'date', 'end_date', 'start', 'end',
  'price', 'payment', 'beginner_class', 'music', 'dj', 'band', 'organizer',
  'url', 'description', 'status',
];
const SERIES_FIELDS = [
  'id', 'name', 'style', 'venue_id', 'weekday', 'start', 'end', 'price',
  'payment', 'beginner_class', 'music', 'dj', 'band', 'organizer', 'url',
  'description', 'status', 'valid_from', 'valid_to',
];

const val = (row, col) => (row[col] ?? '').trim();
const isDateShape = (s) => /^\d{4}-\d{2}-\d{2}$/.test(s);
const formatRow = (row, cols) => Papa.unparse([row], { header: false, columns: cols });

// Today in Europe/Stockholm (en-CA formats as YYYY-MM-DD) — matches
// scrape.mjs and validate-data.mjs's notion of "today".
function stockholmToday() {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Europe/Stockholm', year: 'numeric', month: '2-digit', day: '2-digit',
  }).format(new Date());
}

function readDataset(file) {
  const p = path.join(DATA_DIR, `${file}.csv`);
  if (!existsSync(p)) return { fields: [], rows: [] };
  const parsed = Papa.parse(readFileSync(p, 'utf-8'), { header: true, skipEmptyLines: true });
  return { fields: parsed.meta.fields ?? [], rows: parsed.data };
}

function main() {
  const venues = readDataset('venues');
  const series = readDataset('series');
  const exceptions = readDataset('exceptions');
  const oneoffs = readDataset('oneoffs');
  const bands = readDataset('bands');
  const today = stockholmToday();

  const endedOneoffs = [];
  for (const row of oneoffs.rows) {
    if (val(row, 'status') !== 'live') continue;
    const date = val(row, 'date');
    const endDate = val(row, 'end_date');
    const last = isDateShape(endDate) ? endDate : date;
    if (!isDateShape(last) || last >= today) continue;
    endedOneoffs.push({ id: val(row, 'id'), name: val(row, 'name'), last, row: { ...row, status: 'ended' } });
  }

  const endedSeries = [];
  for (const row of series.rows) {
    if (val(row, 'status') !== 'live') continue;
    const validTo = val(row, 'valid_to');
    if (!isDateShape(validTo) || validTo >= today) continue;
    endedSeries.push({ id: val(row, 'id'), name: val(row, 'name'), validTo, row: { ...row, status: 'ended' } });
  }

  if (endedOneoffs.length === 0 && endedSeries.length === 0) {
    const report = `## Mark ended — nothing to do\n\nNo \`live\` rows are past their end date as of ${today}.\n\n🤖 Generated by \`scripts/mark-ended.mjs\`\n`;
    writeFileSync(REPORT_PATH, report);
    process.stdout.write(report);
    console.log('\nNo rows to mark ended.');
    return;
  }

  const oneoffsLines = readFileSync(ONEOFFS_PATH, 'utf-8').replace(/\n+$/, '').split('\n');
  for (const { id, row } of endedOneoffs) {
    const i = oneoffsLines.findIndex((ln) => ln.startsWith(`${id},`));
    if (i >= 0) oneoffsLines[i] = formatRow(row, ONEOFF_FIELDS);
  }
  const oneoffsText = `${oneoffsLines.join('\n')}\n`;

  const seriesLines = readFileSync(SERIES_PATH, 'utf-8').replace(/\n+$/, '').split('\n');
  for (const { id, row } of endedSeries) {
    const i = seriesLines.findIndex((ln) => ln.startsWith(`${id},`));
    if (i >= 0) seriesLines[i] = formatRow(row, SERIES_FIELDS);
  }
  const seriesText = `${seriesLines.join('\n')}\n`;

  // Delta validation gate, same shape as scrape.mjs: block (write nothing)
  // only on errors this run introduces. Flipping live->ended should only ever
  // fix pre-existing errors, never add one, but the gate is cheap insurance.
  const baseErrors = new Set(
    validateData({ venues, series, exceptions, oneoffs, bands }, { today }).errors
  );
  const reOneoffs = Papa.parse(oneoffsText, { header: true, skipEmptyLines: true });
  const reSeries = Papa.parse(seriesText, { header: true, skipEmptyLines: true });
  const afterErrors = validateData({
    venues,
    series: { fields: reSeries.meta.fields ?? [], rows: reSeries.data },
    exceptions,
    oneoffs: { fields: reOneoffs.meta.fields ?? [], rows: reOneoffs.data },
    bands,
  }, { today }).errors;
  const newErrors = afterErrors.filter((e) => !baseErrors.has(e));

  const report = buildReport({ endedOneoffs, endedSeries, today, newErrors });
  writeFileSync(REPORT_PATH, report);
  process.stdout.write(report);

  if (newErrors.length) {
    console.error(`\n✖ marking ended introduced ${newErrors.length} schema error(s) — not writing.`);
    process.exit(1);
  }

  if (DRY_RUN) {
    console.log(`\n[dry-run] ${endedOneoffs.length} one-off(s), ${endedSeries.length} series row(s) — nothing written.`);
    return;
  }
  if (endedOneoffs.length) writeFileSync(ONEOFFS_PATH, oneoffsText);
  if (endedSeries.length) writeFileSync(SERIES_PATH, seriesText);
  console.log(`\nMarked ${endedOneoffs.length} one-off(s) and ${endedSeries.length} series row(s) ended.`);
}

function buildReport({ endedOneoffs, endedSeries, today, newErrors }) {
  const lines = ['## Mark ended events', '', `Reference date: ${today} (Europe/Stockholm).`, ''];

  lines.push(`### One-offs marked \`ended\` (${endedOneoffs.length})`);
  for (const o of endedOneoffs) lines.push(`- \`${o.id}\`  ${o.name}  (last day ${o.last})`);
  lines.push('');

  lines.push(`### Series marked \`ended\` (${endedSeries.length})`);
  for (const s of endedSeries) lines.push(`- \`${s.id}\`  ${s.name}  (valid_to ${s.validTo})`);
  lines.push('');

  if (newErrors.length) {
    lines.push('### ❌ Schema errors introduced (not written)');
    lines.push(...newErrors.map((e) => `- ${e}`));
    lines.push('');
  }

  lines.push('🤖 Generated by `scripts/mark-ended.mjs`');
  return `${lines.join('\n')}\n`;
}

main();
